# Generated by Django 3.0.7 on 2023-02-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(help_text='Enter the movie detail URL.', null=True, verbose_name='URL'),
        ),
    ]
