# Generated by Django 3.0.7 on 2023-02-08 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_movie_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='url',
        ),
        migrations.AddField(
            model_name='movie',
            name='movierating',
            field=models.CharField(choices=[('PG', 'PG'), ('PG-13', 'PG-13'), ('G', 'G'), ('R', 'R')], default='G', max_length=10),
        ),
    ]
