# Generated by Django 3.0.7 on 2023-02-09 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230208_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='website',
            field=models.URLField(help_text='Enter the movie/show URL.', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='watchrating',
            field=models.CharField(choices=[('G', 'G'), ('R', 'R'), ('PG', 'PG'), ('PG-13', 'PG-13')], default='G', max_length=10),
        ),
    ]
